# @package _global_

name: yuv_resnet
project_root: /home/ayb/resnet-training

trainer:
  gpus: [0]

early_stopping_patience: 30

defaults:
  - datamodule: imagenet.yaml
  - model: yuvresnet.yaml
  - optimizer: adam.yaml
  - scheduler: reducelronplateau.yaml
