name: bottleneck_training
project_path: /home/ayb/resnet-training
data:
  dataset_path: /home/ayb/Documents/datasets/ILSVRC
  num_workers_factor: 8
  input_shape: [128, 128]
  pin_memory: True

trainer:
  gpus: [0]

hparams:
  lr: 0.01
  lr_scheduler:
    factor: 0.5
    patience: 10
  batch_size: 128
  early_stopping_patience: 30

