name: bottleneck_training
project_path: /home/ayb/resnet-training
data:
  dataset_path: /home/ayb/Documents/datasets/TinyImageNet-200
  num_workers_factor: 4

trainer:
  gpus: [0]

hparams:
  lr: 0.001
  lr_scheduler:
    factor: 0.5
    patience: 10
  batch_size: 32
  early_stopping_patience: 30

